
# Modelagem

Sed est quam, aliquet vel augue vitae, sodales tristique nulla. Maecenas tincidunt porttitor posuere. Aenean et aliquam mauris. Suspendisse potenti. Praesent feugiat, lorem ac interdum tempus, metus ipsum iaculis turpis, et maximus leo purus in augue. Curabitur non viverra diam. Nam eu maximus ante, vel auctor dolor. Suspendisse a magna sodales, hendrerit diam at, finibus ligula. Donec dolor sem, egestas in risus quis, pharetra ullamcorper ipsum.

Como vimos no Capítulo \@ref(descritiva), integer arcu metus, dictum sit amet venenatis non, cursus eu turpis. Donec a leo hendrerit, viverra tortor id, porttitor orci. Nam nec libero lobortis, congue enim nec, congue justo. Donec elementum velit ut consequat lacinia. Aenean dictum aliquet purus at vestibulum. 

O Capítulo [Análise descritiva] In hac habitasse platea dictumst. Quisque in ipsum diam. Vivamus venenatis ullamcorper eros et bibendum. Vivamus consequat ullamcorper rutrum.

[Aqui](#descritiva) falamos sobre pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin id eleifend ante, vel imperdiet urna. Suspendisse tincidunt ante ligula, tempor convallis lectus ultricies et.

\newpage

```{r, echo = FALSE, warning=FALSE, message = FALSE}
tab_modelo <- ssp |> 
  filter(ano %in% 2017:2020) |> 
  group_by(data, regiao_nome) |> 
  summarise(
    across(
      estupro:vit_latrocinio,
      sum
    )
  )

fit <- lm(roubo_total ~ regiao_nome + hom_tentativa + lesao_corp_dolosa, data = tab_modelo)

broom::tidy(fit) |> 
  mutate(
    across(
      where(is.numeric),
      round,
      digits = 2
    )
  ) |> 
  knitr::kable(caption = "Resultado do nosso modelo.")
```

Etiam ultrices tellus et eros vestibulum luctus quis at ligula. Donec id feugiat lorem. Duis libero ante, viverra in lobortis at, sollicitudin ut ante. Maecenas ut volutpat nunc. Morbi porttitor turpis sit amet tempor hendrerit. Ut urna augue, molestie a quam in, ornare pharetra urna. Integer eu magna eget odio aliquam placerat. Aliquam molestie vulputate nibh. Ut venenatis justo in orci eleifend consectetur. Sed elementum dictum fermentum. Etiam viverra tortor id justo interdum commodo. Pellentesque finibus, leo a aliquet molestie, quam massa maximus magna, non euismod dui quam condimentum lectus. Ut semper mattis libero, at dictum lacus commodo in. Fusce pharetra neque libero, sit amet feugiat erat maximus sed.

Nulla et arcu volutpat, condimentum ipsum ac, gravida felis. Vivamus erat tellus, tincidunt at felis in, dignissim sagittis nisi. Nam viverra semper ex. Nam posuere tempus massa ut feugiat. Quisque lorem erat, tempus id interdum eu, dignissim suscipit nisi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed scelerisque nisi eu finibus scelerisque.
